version: "3.8"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.128.0.0/16

services:
  archive:
    stdin_open: true
    tty: true
    container_name: archive-web
    restart: no
    ports:
      - 7443:80
    volumes:
      - /home/media2/dev/www/archive/db:/db
      - /home/media2/documents:/home/media2/documents
      - /home/media2/dev/www/archive/backend:/var/www/html
    environment:
      - TZ=Europe/Berlin
    image: archive:latest
    networks:
      default:
        ipv4_address: 172.128.0.2
    healthcheck:
      test: [ "CMD-SHELL", " netstat -an | grep -q 80" ]

  zigbee2mqtt:
    container_name: archive-solr
    image: solr
    restart: no
    ports:
      - 8983:8983
    volumes:
      - /home/media2/documents:/home/media2/documents
    environment:
      - TZ=Europe/Berlin
    networks:
      default:
        ipv4_address: 172.128.0.3
