version: "3.8"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  mosquitto:
    stdin_open: true
    tty: true
    container_name: home-mqtt
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9002:9001
    volumes:
      - /home/media2/docker/volumes/home/mqtt-config:/mosquitto/config
      - /home/media2/docker/volumes/home/mqtt-data:/mosquitto/data
      - /home/media2/docker/volumes/home/mqtt-log:/mosquitto/log
    image: eclipse-mosquitto
    networks:
      default:
        ipv4_address: 172.18.0.3
    healthcheck:
      test: [ "CMD-SHELL", " netstat -an | grep -q 1883" ]

  zigbee2mqtt:
    container_name: home-zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: no
    ports:
      - 8080:8080
    volumes:
      - /home/media2/docker/volumes/home/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Berlin
    networks:
      default:
        ipv4_address: 172.18.0.5
    healthcheck:
      test: [ "CMD-SHELL", " netstat -an | grep -q 8080" ]
    depends_on:
      mosquitto:
        condition: service_healthy

  homeassistant:
    container_name: home-homeassistant
    image: homeassistant/home-assistant:latest
    volumes:
      - /home/media2/docker/volumes/home/homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123
      - 9003:9003
    networks:
      default:
        ipv4_address: 172.18.0.4
    healthcheck:
      test: [ "CMD-SHELL", " netstat -an | grep -q 8123" ]
    depends_on:
      zigbee2mqtt:
        condition: service_healthy

  nodered:
    container_name: home-nodered
    image: nodered/node-red
    restart: no
    ports:
      - "1880:1880/tcp"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /home/media2/docker/volumes/home/nodered-data:/data
      - /home/media2/dev/smarthome/container/ext_data:/ext_data
    networks:
      default:
        ipv4_address: 172.18.0.2
    depends_on:
      homeassistant:
        condition: service_healthy
